---
- name: Converge
  hosts: consul_instances
  become: true
  become_user: root
  any_errors_fatal: true
  roles:
    - role: brianshumate.consul
      consul_group_name: consul_instances
    - role: lean_delivery.ggr
    - role: ansible-role-consul-template
  vars:
    consul_raw_key: ''
